name: Deploy to ECS

on:
  push:
    branches:
      - master  # Adjust to your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::908027411127:role/GitHubActionsECRandECSRole  # Your IAM role ARN
          aws-region: eu-north-1  # Specify the region here

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_DEFAULT_REGION: eu-north-1

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          service: my-app-service
          cluster: my-app-cluster
          wait-for-service-stability: true
